### ISSUE TITLE
GPT Pricing Note

### ISSUE THREAD

**Issue by MatthewCochrane** [360macky/generative-manim#2]
https://github.com/360macky/generative-manim/blob/5ac9049d15c6151bfc0a07d000a58b59833ec16d/src/pages/3_%E2%9A%A1%EF%B8%8F_How_it_works.py#L52

Note that GPT4 costs 3 (input) to 6 (generated) cents for 1000 tokens, so you actually get more like 1 million tokens for $30.

Reference: https://openai.com/pricing

**Comment by 360macky** [comment]
Ohh, I didn't notice that. Thank you. I'll update the paragraph.
